pipeline { 
    agent any 
    stages { 
        stage('Descargar código') { 
            steps { 
                checkout scm
            } 
        } 
        stage('Validar PHP') { 
            steps { 
                // Valida la sintaxis de tu archivo PHP principal antes de moverlo
                sh 'php -l api/index.php' 
            } 
        } 
        stage('Desplegar en Apache') { 
            steps { 
                // Copia los archivos de tu backend a la carpeta pública de Apache
                sh 'sudo cp -r api/* /var/www/html/cv_site/'
                // Le dice a Apache que recargue los nuevos ficheros tal como pide la guía
                sh 'sudo systemctl reload apache2'
            } 
        } 
    } 
}